name: Update README Download Count
run-name: Updaing download count

on:
  schedule:
  - cron: "0 12 * * 6"
  workflow_dispatch:

jobs:
  job1:
    name: Update download count
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2
      - name: Modifiy the specific files using scripts
        run: |
          sh ./update-badge.sh
          git config --global user.name "Github Action"
          git config --global user.email "FireIsGood@users.noreply.github.com"
          
          git add -A
          git commit -m "Chore: Update download count"
          git push
